# Autogenerated by devscripts/update-version.py

__version__ = '2025.08.01.161255'

RELEASE_GIT_HEAD = 'ead42b8a9ba552ea4682f98fc754087dd5e948a6'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'hydro63/yt-dlp'

ORIGIN = 'hydro63/yt-dlp'

_pkg_version = '2025.08.01.161255'
