# Autogenerated by devscripts/update-version.py

__version__ = '2025.09.21.120124'

RELEASE_GIT_HEAD = 'c9f8f21926b91cbd2bc1b0bbe3f863b2b9a34761'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'hydro63/yt-dlp'

ORIGIN = 'hydro63/yt-dlp'

_pkg_version = '2025.09.21.120124'
